services:
  - type: web
    name: sendo
    env: node
    plan: starter
    numInstances: 1
    envVars:
      - key: PORT
        value: 10000
      - key: SERVE_WEB
        value: "true"
      - key: FRONTEND_BASE
        value: "https://sendo-ebook.vercel.app/"
    buildCommand: |
      npm --prefix server ci
      npm --prefix web ci
      npm --prefix web run build
    startCommand: cd server && node server.js
    healthCheckPath: /api/health
